### ISSUE TITLE
Multiple And operator not working

### ISSUE THREAD

**Issue by fabiohvp** [manadart/Enflow#1]
Hello, I'm having problem using the following rules:

My test table is like this:
Configuration //Id is auto incremental
Id   | Code   | Value
1    | "a"       | "value1"
2    | "b"       | "value2"

I'm trying to insert this new configuration
Configuration configuration = new Configuration(){ Code = "c", Value = "not empty" };

var rules = new CodeNotEmpty().And(ValueNotEmpty()).And(CodeIsUnique());

var satisfied = rules.IsSatisfied(configuration); //it is false, but should be true

But if I do this way, it works:
var rules2 = new CodeNotEmpty().And(ValueNotEmpty());

var satisfied2 = rules2.IsSatisfied(configuration) && new CodeIsUnique().IsSatisfied(configuration); //this is true, as it should be

public class CodeNotEmpty: StateRule<Configuration>
    {
        public override Expression<Func<Configuracao, bool>> Predicate
        {
            get { return o => o.Code != null && o.Code.Trim() != string.Empty; }
        }
    }

public class ValueNotEmpty: StateRule<Configuration>
    {
        public override Expression<Func<Configuracao, bool>> Predicate
        {
            get { return o => o.Value != null && o.Value.Trim() != string.Empty; }
        }
    }

public class CodeIsUnique: StateRule<Configuration>
    {
        public override Expression<Func<Configuracao, bool>> Predicate
        {
            get { 
Database database = new Database();
                return o => !database.GetTable< Configuration >().Any(p => p.Id != o.Id && p.Code == o.Code);
            }
        }
    }

By the way, if there is any syntax error, please ignore because I did translate the code, and it can be missing a few characters..

And thank you for this great job, I loved this library, very pratical and easy to use.

**Comment by fabiohvp** [comment]
I found out the problem, when the method ReplaceParameter create the Expression.Lambda, it does not recognize the object Database.

I tried to pass it as parameter, but I had no luck =/

Since the problem is no the library itself, I am closing this issue.

**Comment by manadart** [comment]
Hi there,

Sorry I didn't reply to this sooner - it was buried in my deluged inbox. I'm glad to see you got over the hump there.

Thanks for your kind words. I'm glad you're finding this library of some use. I haven't been writing C# for money for some time now, and so haven't been using the library myself in any new projects. Consequently, it hasn't had new contributions for a while.

Feel free to send suggestions, or PRs. I'll be glad to get the feedback.

All the best,
Joe
